### ISSUE TITLE
Add motor stop integration

### ISSUE THREAD

**Issue by domitto** [osprey-dcs-mct/cs-vbm#3]
Make sure all the movement can be aborted/stopped from a single PV:
- DFanout record will set the STOP field of the underlying records

**Comment by waynelewis** [comment]
We should also tie this into the STOP output of the Soft Channel motor records using the `.STOO` field.

**Comment by domitto** [comment]
Should we call sync after the stop command with an FLNK link?

**Comment by waynelewis** [comment]
> Should we call sync after the stop command with an FLNK link?

That would be worth trying. See how it goes and if it behaves well, I'd say include it.
